#############################################################################
# Makefile for building: execs/gpx-tests
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  GPX-Tests.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile GPX-Tests.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++0x -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Iheaders -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gpx-tests1.0.0
DISTDIR = /home/jm/git/softEndTask7/.tmp/gpx-tests1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -lboost_unit_test_framework 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/earth.cpp \
		src/geometry.cpp \
		src/logs.cpp \
		src/position.cpp \
		src/route.cpp \
		src/track.cpp \
		src/xmlparser.cpp \
		src/gpx-tests/name.cpp \
		src/gpx-tests/totalLength-t0068955.cpp \
		src/gpx-tests.cpp \
		src/gpx-tests/netHeightGain_n0689061.cpp \
		src/gpx-tests/name.cpp \
		src/gpx-tests/totalHeightGain-N0720387.cpp \
		src/gpx-tests/minLatTests_N0720717.cpp \
		src/gpx-tests/maxElevation-n0686300.cpp \
		src/gpx-tests/netLength_n0641701.cpp \
		src/gpx-tests/n0703481_maxelevationtests.cpp \
		src/gpx-tests/n0494166MaximumLongitude.cpp \
		src/gpx-tests/n0680788-minElevationTests.cpp \
		src/gpx-tests/array-operator.cpp \
		src/gpx-tests/n0695913.cpp \
		src/gpx-tests/maxGradient-N0697611.cpp \
		src/gpx-tests/route-constructor-tests.cpp \
		src/gpx-tests/route-buildReport-tests.cpp 
OBJECTS       = earth.o \
		geometry.o \
		logs.o \
		position.o \
		route.o \
		track.o \
		xmlparser.o \
		name.o \
		totalLength-t0068955.o \
		gpx-tests.o \
		netHeightGain_n0689061.o \
		name.o \
		totalHeightGain-N0720387.o \
		minLatTests_N0720717.o \
		maxElevation-n0686300.o \
		netLength_n0641701.o \
		n0703481_maxelevationtests.o \
		n0494166MaximumLongitude.o \
		n0680788-minElevationTests.o \
		array-operator.o \
		n0695913.o \
		maxGradient-N0697611.o \
		route-constructor-tests.o \
		route-buildReport-tests.o
DIST          = src/gpx-tests/route-buildReport-output.txt \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GPX-Tests.pro headers/earth.h \
		headers/geometry.h \
		headers/logs.h \
		headers/position.h \
		headers/route.h \
		headers/track.h \
		headers/types.h \
		headers/xmlparser.h src/earth.cpp \
		src/geometry.cpp \
		src/logs.cpp \
		src/position.cpp \
		src/route.cpp \
		src/track.cpp \
		src/xmlparser.cpp \
		src/gpx-tests/name.cpp \
		src/gpx-tests/totalLength-t0068955.cpp \
		src/gpx-tests.cpp \
		src/gpx-tests/netHeightGain_n0689061.cpp \
		src/gpx-tests/name.cpp \
		src/gpx-tests/totalHeightGain-N0720387.cpp \
		src/gpx-tests/minLatTests_N0720717.cpp \
		src/gpx-tests/maxElevation-n0686300.cpp \
		src/gpx-tests/netLength_n0641701.cpp \
		src/gpx-tests/n0703481_maxelevationtests.cpp \
		src/gpx-tests/n0494166MaximumLongitude.cpp \
		src/gpx-tests/n0680788-minElevationTests.cpp \
		src/gpx-tests/array-operator.cpp \
		src/gpx-tests/n0695913.cpp \
		src/gpx-tests/maxGradient-N0697611.cpp \
		src/gpx-tests/route-constructor-tests.cpp \
		src/gpx-tests/route-buildReport-tests.cpp
QMAKE_TARGET  = gpx-tests
DESTDIR       = execs/#avoid trailing-slash linebreak
TARGET        = execs/gpx-tests


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d execs/ || mkdir -p execs/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GPX-Tests.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GPX-Tests.pro
	$(QMAKE) -o Makefile GPX-Tests.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
GPX-Tests.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile GPX-Tests.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

earth.o: src/earth.cpp headers/geometry.h \
		headers/types.h \
		headers/earth.h \
		headers/position.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o earth.o src/earth.cpp

geometry.o: src/geometry.cpp headers/geometry.h \
		headers/types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geometry.o src/geometry.cpp

logs.o: src/logs.cpp headers/logs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logs.o src/logs.cpp

position.o: src/position.cpp headers/geometry.h \
		headers/types.h \
		headers/earth.h \
		headers/position.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o position.o src/position.cpp

route.o: src/route.cpp headers/xmlparser.h \
		headers/geometry.h \
		headers/types.h \
		headers/earth.h \
		headers/position.h \
		headers/route.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o route.o src/route.cpp

track.o: src/track.cpp headers/geometry.h \
		headers/types.h \
		headers/xmlparser.h \
		headers/track.h \
		headers/position.h \
		headers/route.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o track.o src/track.cpp

xmlparser.o: src/xmlparser.cpp headers/xmlparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlparser.o src/xmlparser.cpp

name.o: src/gpx-tests/name.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o name.o src/gpx-tests/name.cpp

totalLength-t0068955.o: src/gpx-tests/totalLength-t0068955.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o totalLength-t0068955.o src/gpx-tests/totalLength-t0068955.cpp

gpx-tests.o: src/gpx-tests.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpx-tests.o src/gpx-tests.cpp

netHeightGain_n0689061.o: src/gpx-tests/netHeightGain_n0689061.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netHeightGain_n0689061.o src/gpx-tests/netHeightGain_n0689061.cpp

name.o: src/gpx-tests/name.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o name.o src/gpx-tests/name.cpp

totalHeightGain-N0720387.o: src/gpx-tests/totalHeightGain-N0720387.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o totalHeightGain-N0720387.o src/gpx-tests/totalHeightGain-N0720387.cpp

minLatTests_N0720717.o: src/gpx-tests/minLatTests_N0720717.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minLatTests_N0720717.o src/gpx-tests/minLatTests_N0720717.cpp

maxElevation-n0686300.o: src/gpx-tests/maxElevation-n0686300.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxElevation-n0686300.o src/gpx-tests/maxElevation-n0686300.cpp

netLength_n0641701.o: src/gpx-tests/netLength_n0641701.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netLength_n0641701.o src/gpx-tests/netLength_n0641701.cpp

n0703481_maxelevationtests.o: src/gpx-tests/n0703481_maxelevationtests.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o n0703481_maxelevationtests.o src/gpx-tests/n0703481_maxelevationtests.cpp

n0494166MaximumLongitude.o: src/gpx-tests/n0494166MaximumLongitude.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o n0494166MaximumLongitude.o src/gpx-tests/n0494166MaximumLongitude.cpp

n0680788-minElevationTests.o: src/gpx-tests/n0680788-minElevationTests.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o n0680788-minElevationTests.o src/gpx-tests/n0680788-minElevationTests.cpp

array-operator.o: src/gpx-tests/array-operator.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o array-operator.o src/gpx-tests/array-operator.cpp

n0695913.o: src/gpx-tests/n0695913.cpp headers/logs.h \
		headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o n0695913.o src/gpx-tests/n0695913.cpp

maxGradient-N0697611.o: src/gpx-tests/maxGradient-N0697611.cpp headers/geometry.h \
		headers/types.h \
		headers/logs.h \
		headers/route.h \
		headers/position.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxGradient-N0697611.o src/gpx-tests/maxGradient-N0697611.cpp

route-constructor-tests.o: src/gpx-tests/route-constructor-tests.cpp headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h \
		headers/logs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o route-constructor-tests.o src/gpx-tests/route-constructor-tests.cpp

route-buildReport-tests.o: src/gpx-tests/route-buildReport-tests.cpp headers/route.h \
		headers/types.h \
		headers/position.h \
		headers/track.h \
		headers/logs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o route-buildReport-tests.o src/gpx-tests/route-buildReport-tests.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

