
GPXLogGenerator: GPXLogGenerator.cpp
	g++ GPXLogGenerator.cpp position.cpp earth.cpp geometry.cpp gridworld_route.cpp gridworld.cpp xmlgenerator.cpp logs.cpp -I ../headers -o GPXLogGenerator

clean:
	rm -rf GPXLogGenerator
